apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: ms-fiapburger-produto
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      initContainers:
        - name: init-mongo
          image: mongo:4.0.3
          command: ['sh', '-c', 'mongo ${MONGO_URL} < /docker-entrypoint-initdb.d/initdb.js']
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-url
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      containers:
        - name: mongo
          image: mongo:4.0.3
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-url
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "256Mi"
              cpu: "400m"
              ephemeral-storage: "1Gi"
      volumes:
        - name: initdb
          configMap:
            name: mongo-initdb-configmap
