apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: ms-fiapburger-produto
type: Opaque
data:
  mongo-url: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvcHJvZHV0by1tb25nby1tb25nb2Ri  # 'mongodb://mongodb:27017/produto-mongo-mongodb' encoded in base64