apiVersion: v1
kind: Service
metadata:
  name: fiap-burger-api-svc
  namespace: ms-fiapburger-produto
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  selector:
    app: ms-produto
