apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-produto-deployment
  namespace: ms-fiapburger-produto
  labels:
    app: ms-produto-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-produto
  template:
    metadata:
      labels:
        app: ms-produto
    spec:
      containers:
        - name: ms-produto
          image: alexcesarnascimento/ms-produto:0.0.1
          command: ["npm", "start"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          ports:
            - containerPort: 5050
              protocol: TCP
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-url