name: Demo to create automatic PR

on:
  push:
    branches:
      - 'feature/**'
permissions:
  pull-requests: write

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17'

      - name: Install dependencies
        run: npm install

#      - name: Run unit tests
#        run: npm test

#      - name: Install SonarCloud Scanner
#        run: npm install -g sonar-scanner

#      - name: Run SonarCloud scan
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: |
#          sonar-scanner \
#          -Dsonar.projectKey=my_project_key \
#          -Dsonar.organization=my_organization \
#          -Dsonar.sources=. \
#          -Dsonar.host.url=https://sonarcloud.io \
#          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ github.ref }}
          base: main
          title: "PR AUTOMATICO"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          body: |
            This is to show automatic PR creation
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          delete-branch: false

      - name: PR url
        run: |
          echo "Pull Request URL - ${{ steps.create_pr.outputs.pull-request-url }}"
          echo "Deploying to production server on branch $GITHUB_REF"
