name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17'

      - name: Install dependencies
        run: npm install

      - name: Run linting and tests
        run: |
          npm run lint  # Adjust to your linting script
          npm test

      - name: Build project
        run: npm run build  # Adjust to your build script if necessary

      - name: Build Docker image
        run: |
          docker build -t alexcesarnascimento/ms-produto:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: | 
          docker push alexcesarnascimento/ms-produto:${{ github.sha }}

      - name: Update Deployment with New Docker Image
        run: |
          sed -i 's|alexcesarnascimento/ms-produto:.*|alexcesarnascimento/ms-produto:${{ github.sha }}|' kubernetes/ms-produto.deployment.yaml

      - name: Clean up old resources
        run: |
          kubectl delete namespace ms-fiapburger-produto
        continue-on-error: true

      - name: Deploy to Kubernetes/EKS
        run: |
          kubectl apply -f kubernetes/configmap.yaml
          kubectl apply -f kubernetes/secrets.yaml
          kubectl apply -f kubernetes/service.yaml
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/hpa.yaml

      - name: Notify deployment success
        run: echo "Deployment successful!"

