name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17'

      - name: Install dependencies
        run: npm install

      #      - name: Run linting and tests
      #        run: |
      #          npm run lint  # Adjust to your linting script
      #          npm test

      - name: Build project
        run: npm run build  # Adjust to your build script if necessary

      - name: Build Docker image
        run: |
          docker build -t alexcesarnascimento/ms-produto:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push alexcesarnascimento/ms-produto:${{ github.sha }}

      - name: Update Deployment with New Docker Image
        run: |
          sed -i 's|alexcesarnascimento/ms-produto:.*|alexcesarnascimento/ms-produto:${{ github.sha }}|' kubernetes/ms-produto.deployment.yaml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name cluster-fiap --region us-east-1

      - name: Clean up old resources
        run: |
          if kubectl get namespace ms-fiapburger-produto; then
            kubectl delete namespace ms-fiapburger-produto
          else
            echo "Namespace ms-fiapburger-produto does not exist. Skipping deletion."
          fi

      - name: Deploy to Kubernetes/EKS
        run: |
          kubectl apply -f kubernetes/ms-produto.namespace.yaml
          kubectl apply -f kubernetes/mongodb.configmap.yaml
          kubectl apply -f kubernetes/mongodb.secret.yaml
          kubectl apply -f kubernetes/mongodb.pv.yaml
          kubectl apply -f kubernetes/mongodb.pvc.yaml
          kubectl apply -f kubernetes/mongodb.svc.yaml
          kubectl apply -f kubernetes/ms-produto.svc.yaml
          kubectl apply -f kubernetes/mongodb.deployment.yaml
          kubectl apply -f kubernetes/ms-produto.deployment.yaml

      - name: Notify deployment success
        run: echo "Deployment successful!"
